### PR TITLE
Include import in example

### PR DESCRIPTION
**Pull request by kristus123**
I feel this makes the example clearer

### CODE REVIEW

**Comment by kristus123** [comment]
Why was this declined @cryzed?

**Comment by cryzed** [comment]
Because I don't think this addition is sensible. If people can't put 1+1 together when they see this example, they are probably also not capable enough to use the library in the first place.

**Comment by kristus123** [comment]
> Because I don't think this addition is sensible. If people can't put 1+1 together when they see this example, they are probably also not capable enough to use the library in the first place.

Then why have you included imports in the first example?
I think your reason for not having a complete example is flawed. It reminds me of something i would read in
r/gatekeeping. 

Developers come from all over the world with all sorts of different experiences. I bet it would help more than it would hurt. 


Well well, in the end I will respect your opinion.

**Comment by kristus123** [comment]
> Clearly you don't


Of course i do. Is a man not allowed to disagree, but still respect an opinion? Hihi

**Comment by cryzed** [comment]
You didn't just disagree, you implied I'm a gatekeeper because I didn't merge your PR; Anyways, I hope you have a nice day otherwise.

**Comment by kristus123** [comment]
>If people can't put 1+1 together when they see this example, they are probably also not capable enough to use the library in the first place

This was what made it sound like gatekeeping

**Pull request closed without merging**
